### ISSUE TITLE
definition lists problem

### ISSUE THREAD

**Issue by hfl** [textile/textile-lang-com-website#104]
in definition lists, when I write with chinese word "文章", that dt will lost. for example:

- 文章 := 我写了很多文章
- articles := some articles

will output: 

<dl>
	<dt></dt>
	<dt>articles</dt>
	<dd>some articles</dd>
</dl>

**Comment by philwareham** [comment]
Hi. Please can you create an issue for this in the Textile repo instead: https://github.com/textile/php-textile/issues

This repo is specifically for the website, not the language.

Thanks very much!
