### ISSUE TITLE
Random-length HTML comments in HTML results of textile

### ISSUE THREAD

**Issue by jools-r** [textile/textile-lang-com-website#11]
Like the nice new shiny site 👍 !

I appreciate it's early days (you probably know about it) but I saw that the HTML results of the textiled output includes the following at the end of each block:

`<!-- random-length HTML comment: …`

I think @petecooper once explained to me that this a security measure (added by nginx?)

**Comment by petecooper** [comment]
Hey @jools-r - you're right: not a bug, it's a security function. It's a mitigation against the BREACH attack: https://en.wikipedia.org/wiki/BREACH

The comment content and length changes on each page view/refresh, so as to change size and prevent BREACH. See also footer of textpattern.com, textpattern.org etc. This all happens at the Nginx level by way of a module (plugin).

@philwareham: I suggest removing `bug` tag and closing this issue.

**Comment by philwareham** [comment]
@petecooper is there ay way of suppressing that for this website? Not very intuitive to have that comment displayed in user docs output.

**Comment by petecooper** [comment]
Actually, yeah - good point. I didn't spot it was in the that dialog. Will fix.

**Comment by petecooper** [comment]
Follow-up: it's strange that it's appearing in that output box at all -it should be after the closing `html` tag anyway (see source), so is this a glitch with the parser output?

**Comment by philwareham** [comment]
I think the way the interactive Textile on this site works is that it injects a page of HTML called by a Textpattern page template into that output field. I kind of inherited this codebase and hjaven't really chawed that aspect of it but I think that is what happens.

**Comment by petecooper** [comment]
OK, I'll see what we can do in the meantime - other BREACH mitigation involves turning off gzip, which is not ideal but is tidier than having that comment in the output, I guess.

**Comment by philwareham** [comment]
Hold on that Pete - as this outputs a page template I'm sure there is some PHP we can use in that template to strip out the HTML comment on that one page? Not my area but if @bloke or @bloatware may be able to help us?

**Comment by petecooper** [comment]
No worries - I'll sit tight for now and leave as-is. Can you assign me (and whoever else) to this so I can keep track?

**Comment by Bloke** [comment]
Presumably the output gets injected by the [try.txp template](https://github.com/textile/textile-lang-com-website/blob/master/src/templates/pages/try.txp) right? And the results injected into the `html-result` code block in the `default` template?

In which case you should be able to add a line to the `try` template after the call to `TextileThis()`:

```
$result = preg_replace('/<!-- random-length HTML comment: ?.* -->/', '', $result);
```

Untested.

**Comment by jools-r** [comment]
Nice work guys!

**Comment by philwareham** [comment]
Hmm, this comment has reappeared for some reason. Any ideas why?!

**Comment by Bloke** [comment]
Yeah, I spotted that but figured you'd fixed it on a staging server and hadn't made it live.

Two possible reasons:

1) The regex is not matching for some reason.
2) (more likely) if the BREACH comment is added _after_ the PHP runs (as it's an NGINX module) the content is being appended to the PHP so it has no hope of intercepting it beforehand.

If it's (1) we need to ascertain why by dumping content and seeing what matches.
If it's (2) then we'll need to either:

a) fake the BREACH thing in the Txp templates and output them everywhere except the `try` template.
b) find another way to protect the site.
c) turn it off entirely and hope.

**Comment by Bloke** [comment]
The Nginx code that generates it is ludicrously simple: just randomly choose N bytes from A-Za-z0-9, where N is a random number between some largeish range. It could be done in PHP in a cryptographically secure manner with [random_bytes()](http://php.net/manual/en/function.random-bytes.php).

Stick this in a Form and include it below the closing `</html>` tag in every Page template via `<txp:output_form />` _except_ on the `try` page:

```
<txp:php>
$length = random_int(256, 512);
$bytes = random_bytes($length);
echo '<!-- random-length HTML comment: ' . bin2hex($bytes) . ' -->';
</txp:php>
```

That'll create a 512-1024-byte string and append it. Turn off the Nginx module and job done?

**Comment by gocom** [comment]
...it is of course added by the HTTP server to the response body. It is not added to the request, or by PHP-Textile parser to the document.

You could probably mitigate the appearance of the token by setting the response headers properly so that the live editor response is not output as a HTML fragment; like a JSON response. You can then throw whatever token you want in to the JSON object too. Or you could use headers. Heck you could use JWT for authentication too.

Also that live editor implementation is rather unsafe and uses deprecated PHP-Textile methods. For instance, an attacker can send users to `/try` that then serves unsafe user-given HTML document to them within the context of the domain.

You could mitigate that to a degree by sending  the results as JSON, and even further by validating the communication between the live editor and the endpoint with tokens.

**Comment by Bloke** [comment]
Noted. I was thinking as I typed in that box earlier "Hmm, I wonder how this is secured" and it appears the answer is currently "it's not".

I agree making the request a full JSON response is best. Not entirely sure how to validate the tokens (we could compare against `_txp_token` I suppose but I think that's session based not page based, can't recall).

**Comment by philwareham** [comment]
I can make any of you a contributor to this site repo if you wish? I've only really migrated the txstyle.org and re-skinned and modernised it where I can comfortably. My gut feeling is that the user-generation of Textile can probably be handled better/more securely, but that is out of my area of knowledge sorry.

**Comment by gocom** [comment]
> Noted. I was thinking as I typed in that box earlier "Hmm, I wonder how this is secured" and it appears the answer is currently "it's not".

Other issues include the ability to probe any file on the server through PHP-Textile (via image tags), the HTML preview displayed on the website isn't sandboxed (should probably be displayed through a iframe) and then there is the DoS factor of Textile parsing.

> Not entirely sure how to validate the tokens (we could compare against _txp_token I suppose but I think that's session based not page based, can't recall).

You could use [JWT](https://tools.ietf.org/html/rfc7519) to rate-limit and origin-limit the request to a degree... or you could use some proprietary checksum tokens to a same effect.

**Comment by petecooper** [comment]
I've removed the trailing length-hiding block from the site. A few options from my point of view from here since I'm not comfortable leaving it off in perpetuity:

* leave this issue open, rename it so the issue relates to the HTML output contents specifically, or;
* close this issue as it's technically resolved, open a new issue relating to the HTML output contents specifically, or;
* something else I haven't thought of;

**Comment by philwareham** [comment]
I'd suggest closing this issue and if someone wants to open and deal with a new issue regarding how the site outputs live Textile then please so.

I have to move on to other projects so apart from general minor maintenance of the site my involvement is complete as far as I'm concerned. Although I agree the live editor is a security risk and could be done better - that's what we inherited.

Gocom's suggestion of a rate-limiter/checksum seems like there best way forward, without a total rewrite.

**Comment by petecooper** [comment]
OK, closing this - superseded by https://github.com/textile/textile-lang-com-website/issues/32
