### ISSUE TITLE
Add square brackets to superscript/subscript demo textile?

### ISSUE THREAD

**Issue by jools-r** [textile/textile-lang-com-website#118]
Just a suggestion:

Maybe add a second line to the [superscript/subscript](https://textile-lang.com/doc/subscript-and-superscript-text) demo with square brackets to show how to remove the space.

```
Global warming in the 21[^st^] century is mostly caused by CO[~2~] in the atmosphere.
```

**Comment by philwareham** [comment]
OK, done that. Thanks!
