### ISSUE TITLE
UI Suggestion

### ISSUE THREAD

**Issue by AB1908** [textile/textile-lang-com-website#121]
Could we have a Next and Previous bottom at the end of the page? It would certainly help avoid scrolling back to the top to get the link to the next page. Another suggestion I have is to generate a PDF of the entire documentation. It would certainly allow for easier reading. I just came across textile and it seems like the perfect markup tool but the website is hindering my ability to search for the features I'm looking for in the language.

**Comment by philwareham** [comment]
Sure, that can be done. Leave it with me and I'll add those previously/next links in when I get a spare moment.

**Comment by AB1908** [comment]
Thanks a lot and thanks for this amazing tool! I had another question if you could oblige. How do I just parse a text file as input and get an HTML file as an output? From what I could understand in the readme, I don't think it's intended to be used as a CLI tool, is it?

**Comment by philwareham** [comment]
I'll defer to @gocom on that question if I may, as I just handle the website updates. Cheers!

**Comment by AB1908** [comment]
No problem and thanks again!
