### ISSUE TITLE
Deprecation error message at the start of every page

### ISSUE THREAD

**Issue by DenizAksimsek** [textile/textile-lang-com-website#122]
The following message is displayed on the top of all pages:

```
Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/vhosts/textile-lang.com/www/live/textpattern/lib/constants.php on line 136
```

The functionality of the website seems otherwise unaffected.

**Comment by ihalseide** [comment]
I think this issue could be a factor in how the "Try Textile (Editable)" text boxes do not render for me.

![2020-07-12 15 09 07 textile-lang com 015844c6eba8](https://user-images.githubusercontent.com/15919092/87256633-a4881c00-c451-11ea-934a-afa2644c646e.png)

**Comment by philwareham** [comment]
Thanks for the report @DenizAksimsek - I have fixed this now (site was running an older version of Textpattern that had issues with PHP 7.4).

@ihalseide does this also fix your issue, if not then please open as a separate issue and I'll investigate. Please include browser and OS info if you do (I can't replicate that issue on my local install or the live site, in limited testing).

**Comment by ihalseide** [comment]
Issue fixed for me!
