### ISSUE TITLE
Some more CMS and tools supporting Textile markup

### ISSUE THREAD

**Issue by gocom** [textile/textile-lang-com-website#16]
[Here](https://www.textile-lang.com/article/textile-markup-language-support-in-cms). Natively:

* [Sculpin](https://sculpin.io/)

Through extension:

* [Phile](https://github.com/PhileCMS/Phile), [phile/textile](https://github.com/PhileCMS/Textile-Parser-Plugin)

**Comment by philwareham** [comment]
Added now, cheers!
