### ISSUE TITLE
Indentation example doesn't display correctly.

### ISSUE THREAD

**Issue by MarkMon131** [textile/textile-lang-com-website#162]
**Describe the bug**
Indentation example doesn't indent in the example box.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to Indentation section of the documentation.
2. See error

**Expected behaviour**
Text should appear on at various levels of indentation on the left and right of the screen.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser [Firefox]
 - Version [84.0.2]

**Comment by philwareham** [comment]
@petecooper this seems to be a CSP issue - the inline CSS styling will need an `unsafe-inline` declaration on the Textile website to allows this to display as expected.

**Comment by petecooper** [comment]
Will sort, give me 15 mins.

**Comment by petecooper** [comment]
@MarkMon131 - now fixed, thanks for the report and apologies for the turbulence.
