### ISSUE TITLE
Weird sentence in example about images+links

### ISSUE THREAD

**Issue by waldyrious** [textile/textile-lang-com-website#175]
**Describe the bug**
There's an ungrammatical sentence at https://textile-lang.com/doc/links and https://textile-lang.com/doc/images:

> Combine with a link with an image link:
> `!/carver.png!:https://textpattern.com/`

**To reproduce**
Steps to reproduce the behaviour:
1. Go to https://textile-lang.com/doc/links or https://textile-lang.com/doc/images
2. Scroll down to the "More about" section
3. See the incorrect sentence in the list

**Expected behaviour**
I'd expect something like this:

> Combine a link with an image:
> `!/carver.png!:https://textpattern.com/`

ps - I tried to look around for that string in the source code, in order to submit a PR proposing a fix, but I couldn't find it. Is the site content sourced from elsewhere?

**Comment by philwareham** [comment]
Fixed- thanks (FYI the content is within a CMS, hence why you can't see it directly in the repo).

**Comment by waldyrious** [comment]
Thank you!

> FYI the content is within a CMS, hence why you can't see it directly in the repo

Any chance it could be either integrated into this repo, or exposed somehow? It would be nice to allow content changes to be proposed via PRs, as well as the usual benefits of version control.

**Comment by philwareham** [comment]
Unfortunately not unless I change it to a static site or the CMS goes headless - either of which are possibilities in the future.

**Comment by waldyrious** [comment]
Maybe this could be mentioned in the README, then? Because with all the instructions that are currently there for setup and building this project, it's weird that then the content itself is not included :)
