### ISSUE TITLE
content:Textile Escaping methods

### ISSUE THREAD

**Issue by wion** [textile/textile-lang-com-website#18]
Per last couple of posts in this thread: https://github.com/textile/php-textile/issues/185

Maybe have a place somewhere to group all the Textile escaping possibilities, with examples.

**Comment by philwareham** [comment]
Sure, I'm not sure what those are exactly but if someone wants to list them here I'll find a place on the site to document them. Cheers!

**Comment by wion** [comment]
Well, two were in that thread link I provided.

Another is `notextile.` ;)

I think there was at least one more.

The point is, these are not readily apparent to Txp users. I'm not sure they're even documented anywhere except randomly thrown about in the forum, which is not documentation in my opinion.

**Comment by philwareham** [comment]
OK, I've put those two examples of Markdown-like links in the links doc and also mentored it on the endnotes page. Hope that clarifies the syntax?
