### ISSUE TITLE
browser-related issues

### ISSUE THREAD

**Issue by eliph** [textile/textile-lang-com-website#19]
Some examples do not display correctly with FF63 or Safari, such as attributes (alignment, indentation, span, CSS styles). The column layout is broken with IE11

**Comment by philwareham** [comment]
IE11 not supported. I’ll investigate the other issues thanks.

**Comment by philwareham** [comment]
Can you give examples of where the attributes don't work? I've tested alignment of paragraphs and headings and they work as expected.

**Comment by eliph** [comment]
> Can you give examples of where the attributes don't work?

Please find examples the textile-lang.com website. There they don't work. Otherwise yes.

**Comment by philwareham** [comment]
Looks like there is some issue with CSP on the server - it was working a few days back (and works on my local snapshot but I believe @petecooper is migrating everything to a new server. It is also missing some content such as the brand logo so it needs further investigation. Thanks.

**Comment by petecooper** [comment]
I'll take a look now - thanks for the report @eliph.

**Comment by Bloke** [comment]
You beat me to it by [a few seconds](https://github.com/textile/textile-lang-com-website/issues/23) :)

**Comment by philwareham** [comment]
Seems to be CSP issue with `unsafe-inline` CSS missing and for images the img-src `data:`at the very least. Also the site should not be accessible via `www` and should rewrite to simply `textile-lang.com`.

**Comment by petecooper** [comment]
@philwareham yep, editing config now. Please open a new issue with the non-www thing and I'll get onto that next - thanks.

**Comment by philwareham** [comment]
@eliph please revisit the site and refresh browser so it gets latest HTTP header, then let me know if working as expected now? I've quickly tested here and it now seems to be fixed by Pete.

**Comment by eliph** [comment]
much better now 👍

**Comment by philwareham** [comment]
🎉🎂

Thanks all!
