### ISSUE TITLE
CSP prevents logo being displayed

### ISSUE THREAD

**Issue by Bloke** [textile/textile-lang-com-website#23]
Expecting to see the logo at the top of the page. Instead, I see:

```
Content Security Policy: The page's settings blocked the loading of a resource at data:image/svg+xml;charset=utf-8,%3Csvg … ("img-src").
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").
```

**Comment by petecooper** [comment]
I'll take a look - thanks @Bloke.

**Comment by petecooper** [comment]
Should be fixed by https://github.com/textpattern/server-config/commit/91e4175c733ecf68f81aa112e0e2496aa71b5f0a (works fine here, now) - please re-test and close if resolved.

**Comment by philwareham** [comment]
Fixed too, thanks Pete!
