### ISSUE TITLE
Copy edit: Endnotes

### ISSUE THREAD

**Issue by wion** [textile/textile-lang-com-website#26]
https://textile-lang.com/doc/auto-numbered-notes

Should be:

> The sun is reportedly hot,[#hot] just like freshly baked potatoes.[#hot] Ice is cold.[#cold]

I.e. numbers outside of punctuation.

Of course it depends on what style guide you follow, but in this case nearly all of them say 'outside' (but inside a closing bracket or parenthesis).

Too much info time:

MLA was the only guide I knew of that used to advise inside punctuation, but it looks like even they have [changed tune](https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_endnotes_and_footnotes.html). MLA is one of the American humanities versions (next to Chicago Manual) comparable to Oxford's manual of style, or compatibly, the [MHRA](http://www.mhra.org.uk/style), which is what I use in my projects, unless required differently, in conjunction with Oxford's style.

**Comment by philwareham** [comment]
Done. Thanks!
