### ISSUE TITLE
acronym instead of abbr

### ISSUE THREAD

**Issue by colak** [textile/textile-lang-com-website#27]
on https://textile-lang.com/doc/acronyms-abbreviations the html output shows `acronym` instead of `abbr`.

**Comment by Bloke** [comment]
Txp is supposed to use the doctype from prefs as the default doctype for starting Textile site-wide. Check that pref for starters.

Besides that, have a scout through the template code to make sure that 'xhtml' is not being manually passed to any Textile/Parser constructors.

**Comment by philwareham** [comment]
Fixed.
