### ISSUE TITLE
Dead link on implementations page

### ISSUE THREAD

**Issue by Atlas48** [textile/textile-lang-com-website#282]
### Describe the bug
Link on page "[Textile implementations in programming languages](https://textile-lang.com/article/textile-implementations-in-programming-languages)" has a dead link under heading, "OCaml". [komar.bitcheese.net](http://komar.bitcheese.net/en/code/textile-ocaml) does not appear to be an active subdomain.

**Comment by philwareham** [comment]
Fixed now (updated web location). Thanks for the report.
