### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by eliph** [textile/textile-lang-com-website#304]
**Describe the bug**
A forward slash is missing in the "More about: Alignment" example

**To reproduce**
Steps to reproduce the behaviour:
1. Go to the [Alignment page](https://textile-lang.com/doc/text-alignment).
2. Copy the example under "More about: Alignment"
3. Insert into the input box

**Expected behaviour**
The carver image should be displayed

**Comment by philwareham** [comment]
Fixed now, thanks for the report.
