### ISSUE TITLE
horizontal rule

### ISSUE THREAD

**Issue by csonuryilmaz** [textile/textile-lang-com-website#31]
Hi, I couldn't find horizontal rule section on [website](https://textile-lang.com/) :
![horizontal-rule](https://user-images.githubusercontent.com/7355362/50077483-8fa3c200-01f5-11e9-840d-61c9e852528b.png)
[source](http://kyrepo-apps.sourcerepo.com/redmine/kyrepo/help/en-gb/wiki_syntax_detailed.html)

You can check it using VS Code:
![example-textile](https://user-images.githubusercontent.com/7355362/50077511-a4805580-01f5-11e9-840e-5c77dcac190d.png)

Above textile document gives output:
![example-output](https://user-images.githubusercontent.com/7355362/50077535-b235db00-01f5-11e9-9d1f-267790daaeb7.png)

Used extensions on VS Code:
* idleberg.textile
* michaelnewton.textile-preview

**Comment by philwareham** [comment]
That is not part of the native Textile syntax, rather it seems like part of the (extended) Wiki markup.

In Textile you would simple use the standard HTML tag, for example:

```
h3. Testing horizontal rule

line 1

<hr>

line2
```

**Comment by csonuryilmaz** [comment]
@philwareham you're right. :+1: Thanks for the detail, I got it.
