### ISSUE TITLE
Dead link on 'doc/acronyms-abbreviations' page.

### ISSUE THREAD

**Issue by JonathanStreet** [textile/textile-lang-com-website#323]
**Describe the bug**

Point 3 on the page links incorrectly to txstyle.org, rather than textile-lang.com:

> 3. See also [Uppercase words](http://txstyle.org/doc/uppercase-words).

**To reproduce**
Steps to reproduce the behaviour:
1. Go to '[Acronyms and abbreviations](https://textile-lang.com/doc/acronyms-abbreviations)' page.
2. Click on 'Uppercase words'
3. See error.

**Expected behaviour**
The 'Uppercase words' should link to http://textile-lang.com/doc/uppercase-words

**Comment by philwareham** [comment]
Fixed now, thanks for the report.
