### ISSUE TITLE
Bump to 3.7.0?

### ISSUE THREAD

**Issue by petecooper** [textile/textile-lang-com-website#33]
Textile 3.7.0 is out, website is using 3.7.0-dev – bump to 3.7.0 now or wait for Textpattern 4.7.2 to drop?

**Comment by philwareham** [comment]
I'll update as soon as 4.7.2 is out. Leave this issue open so it reminds me. Ta!

**Comment by philwareham** [comment]
Live site is now using Textile 3.7.0
