### ISSUE TITLE
Mention of support for textile on GitHub pages should be removed

### ISSUE THREAD

**Issue by mcavigelli** [textile/textile-lang-com-website#357]
**Describe the bug**
Website says, that textile is supported on GitHub pages.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to https://textile-lang.com/, 1. paragraph
2. Read: "...—also, Textile is supported by GitHub."

**Expected behaviour**
I think this is not the case anymore:
https://github.blog/2016-02-01-github-pages-now-faster-and-simpler-with-jekyll-3-0/#two-additional-changes

**Additional context**
Or have I missed something?

**Comment by philwareham** [comment]
True, they stripped it out a while back to lower their support overheads. I have amended the site now, thanks.
