### ISSUE TITLE
A new extension for Microsoft Visual Studio Code

### ISSUE THREAD

**Issue by GehDoc** [textile/textile-lang-com-website#93]
I just published a new Textile extension for Microsoft Visual Studio Code, there : https://marketplace.visualstudio.com/items?itemName=GehDoc.vscode-textile-preview
Maybe you want to add it to https://textile-lang.com/article/textile-in-ides-and-text-editors ?
Best Regards,
Gérald

**Comment by philwareham** [comment]
Great - I'll do this when I get a spare moment. Cheers.

**Comment by philwareham** [comment]
Done. Thanks for the contribution.
